insert into authors (id,first_name, last_name) values (1,'Drucie', 'Goodbourn');
insert into authors (id,first_name, last_name) values (2,'Marcia', 'Aggiss');
insert into authors (id,first_name, last_name) values (3,'Giovanni', 'Bigg');
insert into authors (id,first_name, last_name) values (4,'Duffie', 'Eynon');
insert into authors (id,first_name, last_name) values (5,'Anselma', 'McKennan');
insert into authors (id,first_name, last_name) values (6,'Gert', 'Kira');
insert into authors (id,first_name, last_name) values (7,'Clerc', 'Djakovic');
insert into authors (id,first_name, last_name) values (8,'Stacee', 'Elsy');
insert into authors (id,first_name, last_name) values (9,'Dorotea', 'Bonhill');
insert into authors (id,first_name, last_name) values (10,'Minni', 'Bunney');
insert into authors (id,first_name, last_name) values (11,'Berty', 'Gandley');
insert into authors (id,first_name, last_name) values (12,'Raynard', 'Tesdale');
insert into authors (id,first_name, last_name) values (13,'Joanna', 'Hutfield');
insert into authors (id,first_name, last_name) values (14,'Dannie', 'Glidder');
insert into authors (id,first_name, last_name) values (15,'Timmie', 'Adshede');
insert into authors (id,first_name, last_name) values (16,'Fernando', 'Neads');
insert into authors (id,first_name, last_name) values (17,'Teddy', 'Guilliland');
insert into authors (id,first_name, last_name) values (18,'Paloma', 'Grebert');
insert into authors (id,first_name, last_name) values (19,'Kristos', 'Usher');
insert into authors (id,first_name, last_name) values (20,'Darcey', 'Rohmer');
insert into authors (id,first_name, last_name) values (21,'Cristie', 'Isacsson');
insert into authors (id,first_name, last_name) values (22,'Lindsay', 'Coutthart');
insert into authors (id,first_name, last_name) values (23,'Helyn', 'Schneidar');
insert into authors (id,first_name, last_name) values (24,'Bette-ann', 'Askem');
insert into authors (id,first_name, last_name) values (25,'Dom', 'Robuchon');

insert into books (id,title, priceOld, price,author) values (1,'exploit real-time e-commerce', '$203.23', '$43.37',1);
insert into books (id,title, priceOld, price,author) values (2,'utilize real-time interfaces', '$260.31', '$35.96',2);
insert into books (id,title, priceOld, price,author) values (3,'extend strategic e-services', '$272.00', '$151.04',3);
insert into books (id,title, priceOld, price,author) values (4,'iterate integrated solutions', '$271.58', '$141.40',4);
insert into books (id,title, priceOld, price,author) values (5,'cultivate magnetic e-commerce', '$278.43', '$54.44',5);
insert into books (id,title, priceOld, price,author) values (6,'architect vertical ROI', '$282.54', '$102.61',6);
insert into books (id,title, priceOld, price,author) values (7,'disintermediate extensible architectures', '$295.38', '$181.27',7);
insert into books (id,title, priceOld, price,author) values (8,'extend leading-edge methodologies', '$283.08', '$97.96',8);
insert into books (id,title, priceOld, price,author) values (9,'integrate one-to-one systems', '$258.51', '$52.25',9);
insert into books (id,title, priceOld, price,author) values (10,'revolutionize 24/7 infrastructures', '$260.79', '$33.69',10);
insert into books (id,title, priceOld, price,author) values (11,'enhance innovative e-services', '$256.54', '$160.98',11);
insert into books (id,title, priceOld, price,author) values (12,'maximize 24/365 e-tailers', '$262.07', '$34.06',12);
insert into books (id,title, priceOld, price,author) values (13,'scale integrated architectures', '$257.66', '$32.97',13);
insert into books (id,title, priceOld, price,author) values (14,'e-enable frictionless web services', '$288.19', '$90.52',14);
insert into books (id,title, priceOld, price,author) values (15,'strategize B2B channels', '$232.27', '$44.83',15);
insert into books (id,title, priceOld, price,author) values (16,'syndicate compelling deliverables', '$287.45', '$101.89',16);
insert into books (id,title, priceOld, price,author) values (17,'utilize bleeding-edge users', '$281.37', '$146.21',17);
insert into books (id,title, priceOld, price,author) values (18,'cultivate 24/365 networks', '$270.99', '$184.76',18);
insert into books (id,title, priceOld, price,author) values (19,'embrace plug-and-play platforms', '$278.36', '$77.71',19);
insert into books (id,title, priceOld, price,author) values (20,'target innovative paradigms', '$298.94', '$130.01',20);
insert into books (id,title, priceOld, price,author) values (21,'generate open-source e-business', '$276.57', '$113.25',21);
insert into books (id,title, priceOld, price,author) values (22,'implement user-centric e-markets', '$254.70', '$115.31',22);
insert into books (id,title, priceOld, price,author) values (23,'utilize magnetic supply-chains', '$279.70', '$77.86',23);
insert into books (id,title, priceOld, price,author) values (24,'e-enable dot-com supply-chains', '$297.83', '$110.15',24);
insert into books (id,title, priceOld, price,author) values (25,'facilitate efficient eyeballs', '$232.30', '$131.48',25);
