DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS books;


CREATE TABLE authors(
id INT PRIMARY KEY ,
first_name VARCHAR(50),
last_name VARCHAR(50)
);

CREATE TABLE  books(
id INT PRIMARY KEY,
title VARCHAR(250) NOT NULL,
priceOld  VARCHAR(250) DEFAULT NULL,
price VARCHAR(250) DEFAULT NULL,
author INT,
FOREIGN KEY(author) REFERENCES authors(id)
);
